name: Update Gist

on:
  push:
    branches:
      - main
    paths:
      - "youtube-music-like-button.user.js"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Read Gist
        id: gist_content
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          action: "get"
          gist_id: ${{ secrets.GIST_ID }}
          file_name: "youtube-music-like-button.user.js"

      - name: Update Gist
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          action: "update"
          gist_id: ${{ secrets.GIST_ID }}
          file_name: "youtube-music-like-button.user.js"
          content: ${{ steps.gist_content.outputs.content }}
