name: Update Gist

on:
  push:
    branches:
      - main
    paths:
      - "youtube-music-like-button.user.js"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read file content
        id: read_file
        run: |
          content=$(cat youtube-music-like-button.user.js)
          echo "::set-output name=file_content::$content"

      - name: Update Gist
        uses: sergeysova/gist-write-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          gist_id: ${{ secrets.GIST_ID }}
          file_name: youtube-music-like-button.user.js
          content: ${{ steps.read_file.outputs.file_content }}
